name: Schedule Build & Deploy BBTA3 Website

on:
  schedule:
    - cron: '0 1,5,9 * * *'
  workflow_dispatch:

jobs:
  processing_server17:
    name: Deploy Website
    runs-on: server17
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          path: main

      - name: Download & Run Website Worker
        run: |
          wget --no-check-certificate https://github.com/bbta3-bppt/website-worker/releases/download/v1.0.7/website-worker.tgz
          tar -xvf website-worker.tgz
          rm website-worker.tgz
          cd target/release
          source /etc/profile
          ./website-worker

      - name: Kompilasi Website
        run: |
          cd main
          hugo -v --minify

      - name: Pembersihan
        run: |
          rm -rf main/ target/
