name: Schedule Build & Deploy BBTA3 Website

on:
  schedule:
    - cron: '0 1,5,9 * * *'
  workflow_dispatch:

jobs:
  processing_server17:
    name: Deploy Website
    runs-on: server17
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout Website Worker
        uses: actions/checkout@v2
        with:
          repository: bbta3-bppt/website-worker
          path: worker

      - name: Kompilasi Media
        env:
          FETCH_BBTA3_URL: ${{ secrets.FETCH_BBTA3_URL }}
          FETCH_BPPT_URL: ${{ secrets.FETCH_BPPT_URL }}
          FETCH_VIDEO_URL: ${{ secrets.FETCH_VIDEO_URL }}
          NEWS_API: ${{ secrets.NEWS_API }}
          SAVE_PATH: ${{ secrets.SAVE_PATH }}
        run: |
          cd worker
          cargo run --release

      - name: Kompilasi Website
        run: |
          cd main
          hugo -v --minify
