name: Build & Deploy BBTA3 Website

on:
  push:
    branches:
      - main
      - master

jobs:
  processing_server17:
    name: Deploy Website
    runs-on: server17
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
        with:
          path: main

      - name: Download & Run Website Worker
        run: |
          mkdir worker
          cd worker
          wget https://github.com/bbta3-bppt/website-worker/releases/download/v1.0.6/website-worker.tgz
          tar -xvf website-worker.tgz
          cd target/release
          cat > ./.env << ENDOFFILE
          NEWS_API=${{ secrets.NEWS_API }}
          FETCH_BBTA3_URL=${{ secrets.FETCH_BBTA3_URL }}
          FETCH_BPPT_URL=${{ secrets.FETCH_BPPT_URL }}
          FETCH_VIDEO_URL=${{ secrets.FETCH_VIDEO_URL }}
          SAVE_PATH=${{ secrets.SAVE_PATH }}
          ENDOFFILE
          ./website-worker

      - name: Kompilasi Website
        run: |
          cd main
          hugo -v --minify

  update_release_draft:
    name: Draft The Release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
