name: Build & Deploy BBTA3 Website

on:
  push:
    branches:
      - main
      - master

jobs:
  processing_server15:
    name: Proses Website Server15
    runs-on: server15
    defaults:
      run:
        shell: bash
        working-directory: /home/server15/www/bbta3/dist
    steps:
      - name: Ambil repositori terbaru
        run: |
          git version
          git pull https://github.com/bbta3-bppt/website.git
      - name: Kompilasi website
        run: |
          hugo -v

  processing_server18:
    name: Proses Website Server18
    runs-on: server18
    defaults:
      run:
        shell: bash
        working-directory: /home/server18/www/bbta3/dist
    steps:
      - name: Ambil repositori terbaru
        run: |
          git version
          git pull https://github.com/bbta3-bppt/website.git
      - name: Kompilasi website
        run: |
          hugo -v

  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
