name: Build & Deploy BBTA3 Website

on:
  push:
    branches:
      - main
      - master

jobs:
  processing_server18:
    name: Proses Website Server17
    runs-on: server17
    steps:
      - name: Checkout Latest Version
        uses: actions/checkout@v2

      - name: Kompilasi website
        run: |
          pwd

  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
