name: Build & Deploy BBTA3 Website

on:
  push:
    branches:
      - master

jobs:
  processing_server1:
    name: Proses Website Server1
    runs-on: server1
    defaults:
      run:
        shell: bash
        working-directory: /var/www/bbta3/v4/
    steps:
      - name: Ambil repositori terbaru
        run: |
          git version
          git pull https://github.com/bbta3-bppt/website.git
      - name: Kompilasi website
        run: |
          hugo -v

  processing_server4:
    name: Proses Website Server4
    runs-on: server4
    defaults:
      run:
        shell: bash
        working-directory: /var/www/bbta3/v4/
    steps:
      - name: Ambil repositori terbaru
        run: |
          git version
          git pull https://github.com/bbta3-bppt/website.git
      - name: Kompilasi website
        run: |
          hugo -v